/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.bug.report;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class SomeSample extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8273109544733464331L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SomeSample\",\"namespace\":\"com.bug.report\",\"fields\":[{\"name\":\"iso\",\"type\":\"string\"},{\"name\":\"continent\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"country\",\"type\":\"string\"}],\"connect.doc\":\"Sample for bug report.\",\"connect.version\":1,\"connect.name\":\"SomeSample\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<SomeSample> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SomeSample> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<SomeSample> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<SomeSample> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<SomeSample> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this SomeSample to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a SomeSample from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a SomeSample instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static SomeSample fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence iso;
  private java.lang.CharSequence continent;
  private java.lang.CharSequence country;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SomeSample() {}

  /**
   * All-args constructor.
   * @param iso The new value for iso
   * @param continent The new value for continent
   * @param country The new value for country
   */
  public SomeSample(java.lang.CharSequence iso, java.lang.CharSequence continent, java.lang.CharSequence country) {
    this.iso = iso;
    this.continent = continent;
    this.country = country;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return iso;
    case 1: return continent;
    case 2: return country;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: iso = (java.lang.CharSequence)value$; break;
    case 1: continent = (java.lang.CharSequence)value$; break;
    case 2: country = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'iso' field.
   * @return The value of the 'iso' field.
   */
  public java.lang.CharSequence getIso() {
    return iso;
  }


  /**
   * Sets the value of the 'iso' field.
   * @param value the value to set.
   */
  public void setIso(java.lang.CharSequence value) {
    this.iso = value;
  }

  /**
   * Gets the value of the 'continent' field.
   * @return The value of the 'continent' field.
   */
  public java.lang.CharSequence getContinent() {
    return continent;
  }


  /**
   * Sets the value of the 'continent' field.
   * @param value the value to set.
   */
  public void setContinent(java.lang.CharSequence value) {
    this.continent = value;
  }

  /**
   * Gets the value of the 'country' field.
   * @return The value of the 'country' field.
   */
  public java.lang.CharSequence getCountry() {
    return country;
  }


  /**
   * Sets the value of the 'country' field.
   * @param value the value to set.
   */
  public void setCountry(java.lang.CharSequence value) {
    this.country = value;
  }

  /**
   * Creates a new SomeSample RecordBuilder.
   * @return A new SomeSample RecordBuilder
   */
  public static com.bug.report.SomeSample.Builder newBuilder() {
    return new com.bug.report.SomeSample.Builder();
  }

  /**
   * Creates a new SomeSample RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SomeSample RecordBuilder
   */
  public static com.bug.report.SomeSample.Builder newBuilder(com.bug.report.SomeSample.Builder other) {
    if (other == null) {
      return new com.bug.report.SomeSample.Builder();
    } else {
      return new com.bug.report.SomeSample.Builder(other);
    }
  }

  /**
   * Creates a new SomeSample RecordBuilder by copying an existing SomeSample instance.
   * @param other The existing instance to copy.
   * @return A new SomeSample RecordBuilder
   */
  public static com.bug.report.SomeSample.Builder newBuilder(com.bug.report.SomeSample other) {
    if (other == null) {
      return new com.bug.report.SomeSample.Builder();
    } else {
      return new com.bug.report.SomeSample.Builder(other);
    }
  }

  /**
   * RecordBuilder for SomeSample instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SomeSample>
    implements org.apache.avro.data.RecordBuilder<SomeSample> {

    private java.lang.CharSequence iso;
    private java.lang.CharSequence continent;
    private java.lang.CharSequence country;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.bug.report.SomeSample.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.iso)) {
        this.iso = data().deepCopy(fields()[0].schema(), other.iso);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.continent)) {
        this.continent = data().deepCopy(fields()[1].schema(), other.continent);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.country)) {
        this.country = data().deepCopy(fields()[2].schema(), other.country);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing SomeSample instance
     * @param other The existing instance to copy.
     */
    private Builder(com.bug.report.SomeSample other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.iso)) {
        this.iso = data().deepCopy(fields()[0].schema(), other.iso);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.continent)) {
        this.continent = data().deepCopy(fields()[1].schema(), other.continent);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.country)) {
        this.country = data().deepCopy(fields()[2].schema(), other.country);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'iso' field.
      * @return The value.
      */
    public java.lang.CharSequence getIso() {
      return iso;
    }


    /**
      * Sets the value of the 'iso' field.
      * @param value The value of 'iso'.
      * @return This builder.
      */
    public com.bug.report.SomeSample.Builder setIso(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.iso = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'iso' field has been set.
      * @return True if the 'iso' field has been set, false otherwise.
      */
    public boolean hasIso() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'iso' field.
      * @return This builder.
      */
    public com.bug.report.SomeSample.Builder clearIso() {
      iso = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'continent' field.
      * @return The value.
      */
    public java.lang.CharSequence getContinent() {
      return continent;
    }


    /**
      * Sets the value of the 'continent' field.
      * @param value The value of 'continent'.
      * @return This builder.
      */
    public com.bug.report.SomeSample.Builder setContinent(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.continent = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'continent' field has been set.
      * @return True if the 'continent' field has been set, false otherwise.
      */
    public boolean hasContinent() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'continent' field.
      * @return This builder.
      */
    public com.bug.report.SomeSample.Builder clearContinent() {
      continent = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'country' field.
      * @return The value.
      */
    public java.lang.CharSequence getCountry() {
      return country;
    }


    /**
      * Sets the value of the 'country' field.
      * @param value The value of 'country'.
      * @return This builder.
      */
    public com.bug.report.SomeSample.Builder setCountry(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.country = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'country' field has been set.
      * @return True if the 'country' field has been set, false otherwise.
      */
    public boolean hasCountry() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'country' field.
      * @return This builder.
      */
    public com.bug.report.SomeSample.Builder clearCountry() {
      country = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public SomeSample build() {
      try {
        SomeSample record = new SomeSample();
        record.iso = fieldSetFlags()[0] ? this.iso : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.continent = fieldSetFlags()[1] ? this.continent : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.country = fieldSetFlags()[2] ? this.country : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SomeSample>
    WRITER$ = (org.apache.avro.io.DatumWriter<SomeSample>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SomeSample>
    READER$ = (org.apache.avro.io.DatumReader<SomeSample>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.iso);

    if (this.continent == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.continent);
    }

    out.writeString(this.country);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.iso = in.readString(this.iso instanceof Utf8 ? (Utf8)this.iso : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.continent = null;
      } else {
        this.continent = in.readString(this.continent instanceof Utf8 ? (Utf8)this.continent : null);
      }

      this.country = in.readString(this.country instanceof Utf8 ? (Utf8)this.country : null);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.iso = in.readString(this.iso instanceof Utf8 ? (Utf8)this.iso : null);
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.continent = null;
          } else {
            this.continent = in.readString(this.continent instanceof Utf8 ? (Utf8)this.continent : null);
          }
          break;

        case 2:
          this.country = in.readString(this.country instanceof Utf8 ? (Utf8)this.country : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










